version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    tufsegm_api:
      image: emvollmer/deep-oc-tufsegm_api
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    tufsegm_api-gpu:
      image: emvollmer/deep-oc-tufsegm_api:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    tufsegm_api-rclone:
      extends:
        service: tufsegm_api
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
